import ffmpeg
import requests
import json

BASE_URL = "http://127.0.0.1:8080"

# 테스트할 데이터
payload_raw = '''
[
  {
    "Question_type": "주관식",
    "Topic": "통일신라",
    "Released": "제2탄",
    "Q_number": 3,
    "mp4": "",
    "Hint": "ㅁㅁㅇ",
    "Answer": "문무왕",
    "Title": "한국사 퀴즈",
    "BG_Image": "https://drive.google.com/file/d/1vjc4FlwhjfiT6Vcb2EE1Jg0FrE3ZcFFR/view?usp=drive_link",
    "Image_": "https://drive.google.com/file/d/1q-EBVO7vfiIh3E5TIVWJqhlpKQjTxyDB/view?usp=drive_link",
    "Question": "통일신라 시대를 연 왕은 누구인가요?",
    "Question_MP3": "https://drive.google.com/file/d/1I_VQpyzDkU48bSIKkpIbnHHKAYK63mYE/view?usp=drive_link",
    "Countdown": "5",
    "Answer_MP3": "https://drive.google.com/file/d/1q4YcCS2HfiS0cTksp4OqrVIBu7HeCJMQ/view?usp=drive_link ",
    "Key_Term": "통일신라,문무왕",
    "Explain": "통일신라 시대는 신라의 문무왕이 삼국을 통일하면서 시작되었습니다. 문무왕의 업적으로는 삼국 통일이 있습니다.",
    "Explain_MP3": "https://drive.google.com/file/d/1LZAhd1qpwkrYl-6lK2hOhnR4qWNFYXnH/view?usp=drive_link",
    "format": {
      "canvasRatio": "1024x768",
      "displayScale": 1,
      "layers": [
        {
          "id": 1753287418385,
          "name": "BG_Image",
          "type": "image",
          "timeMode": "전체",
          "positionMode": "전체",
          "startTime": 0,
          "endTime": 14.2,
          "duration": 14.2,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 0,
          "y": 0,
          "width": 1024,
          "height": 768,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 1,
          "outlineMode": "normal",
          "canvasAlign": "custom",
          "preGap": 0,
          "postGap": 0,
          "linkMode": "absolute",
          "linkedLayerId": null,
          "relativeAnchor": "start",
          "offset": 0,
          "endLinkMode": "auto",
          "endLinkedLayerId": null,
          "endRelativeAnchor": "end",
          "endOffset": 0,
          "imgUrl": "blob:http://localhost:3000/91c99549-ef4f-4e61-95fb-5890edfce4ef",
          "linkedStartLayerId": null,
          "linkedEndLayerId": null
        },
        {
          "id": 1753289346749,
          "name": "Image_",
          "type": "image",
          "timeMode": "전체",
          "positionMode": "부분",
          "startTime": 0,
          "endTime": 14.2,
          "duration": 14.2,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 575.9997979388934,
          "y": 220.9999097966769,
          "width": 300,
          "height": 300,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 0.6,
          "outlineMode": "normal",
          "canvasAlign": "custom",
          "preGap": 0,
          "postGap": 0,
          "linkMode": "absolute",
          "linkedLayerId": null,
          "relativeAnchor": "start",
          "offset": 0,
          "endLinkMode": "auto",
          "endLinkedLayerId": null,
          "endRelativeAnchor": "end",
          "endOffset": 0,
          "imgUrl": "",
          "linkedStartLayerId": null,
          "linkedEndLayerId": null
        },
        {
          "id": 1753287426827,
          "name": "Title",
          "type": "text",
          "timeMode": "전체",
          "positionMode": "부분",
          "startTime": 0,
          "endTime": 14.2,
          "duration": 14.2,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 434,
          "y": 6.000003729925922,
          "width": 200,
          "height": 50,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 0,
          "outlineMode": "normal",
          "canvasAlign": "center",
          "preGap": 0,
          "postGap": 0,
          "linkMode": "absolute",
          "linkedLayerId": null,
          "relativeAnchor": "start",
          "offset": 0,
          "endLinkMode": "auto",
          "endLinkedLayerId": null,
          "endRelativeAnchor": "end",
          "endOffset": 0,
          "text": " 한국사 퀴즈",
          "mp3Key": "Title_mp3",
          "mp3Url": "",
          "mp3PreGap": 0,
          "mp3PostGap": 0,
          "fontSize": 30,
          "color": "#000000",
          "textAlign": "center",
          "verticalAlign": "middle",
          "lineHeight": 1,
          "fontFamily": "BMYEONSUNG",
          "highlight": "",
          "highlightColor": "#0000ff"
        },
        {
          "id": 1753287427268,
          "name": "Question",
          "type": "text",
          "timeMode": "전체",
          "positionMode": "부분",
          "startTime": 0,
          "endTime": 14.2,
          "duration": 14.2,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 178.999939381668,
          "y": 134.00025256930456,
          "width": 700,
          "height": 80,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 0,
          "outlineMode": "normal",
          "canvasAlign": "custom",
          "preGap": 0,
          "postGap": 0,
          "linkMode": "absolute",
          "linkedLayerId": null,
          "relativeAnchor": "start",
          "offset": 0,
          "endLinkMode": "auto",
          "endLinkedLayerId": null,
          "endRelativeAnchor": "end",
          "endOffset": 0,
          "text": "문제",
          "mp3Key": "Question_mp3",
          "mp3Url": "",
          "mp3PreGap": 0,
          "mp3PostGap": 0,
          "fontSize": 30,
          "color": "#000000",
          "textAlign": "left",
          "verticalAlign": "top",
          "lineHeight": 1,
          "fontFamily": "BMYEONSUNG",
          "highlight": "Key_Term",
          "highlightColor": "#ff00ff"
        },
        {
          "id": 1753288039865,
          "name": "Question_MP3",
          "type": "audio",
          "timeMode": "부분",
          "positionMode": "부분",
          "startTime": 0.2,
          "endTime": 3.2,
          "duration": 3,
          "gapBefore": 0,
          "gapAfter": 0.2,
          "x": 50,
          "y": 50,
          "width": 200,
          "height": 50,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 1,
          "outlineMode": "normal",
          "canvasAlign": "custom",
          "preGap": 0,
          "postGap": 0,
          "linkMode": "relative",
          "linkedLayerId": 1753287427268,
          "relativeAnchor": "start",
          "offset": 0.2,
          "endLinkMode": "auto",
          "endLinkedLayerId": null,
          "endRelativeAnchor": "end",
          "endOffset": 0,
          "audioUrl": ""
        },
        {
          "id": 1753287562780,
          "name": "Countdown",
          "type": "countdown",
          "timeMode": "부분",
          "positionMode": "부분",
          "startTime": 3.2,
          "endTime": 8.2,
          "duration": 5,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 451.99874722113844,
          "y": 339.0059387694992,
          "width": 50,
          "height": 50,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 0,
          "outlineMode": "normal",
          "canvasAlign": "custom",
          "preGap": 0,
          "postGap": 0,
          "linkMode": "relative",
          "linkedLayerId": 1753288039865,
          "relativeAnchor": "end",
          "offset": 0,
          "endLinkMode": "auto",
          "endLinkedLayerId": null,
          "endRelativeAnchor": "end",
          "endOffset": 0,
          "countdownStart": 5,
          "fontSize": 50,
          "color": "#ff0000",
          "textAlign": "center",
          "verticalAlign": "middle",
          "fontFamily": "BMYEONSUNG"
        },
        {
          "id": 1753287427893,
          "name": "Hint",
          "type": "text",
          "timeMode": "부분",
          "positionMode": "부분",
          "startTime": 6.2,
          "endTime": 8.2,
          "duration": 2,
          "gapBefore": -2,
          "gapAfter": 0,
          "x": 177.99985855722525,
          "y": 272.0003074386702,
          "width": 200,
          "height": 50,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 0,
          "outlineMode": "normal",
          "canvasAlign": "custom",
          "preGap": 0,
          "postGap": 0,
          "linkMode": "relative",
          "linkedLayerId": 1753287562780,
          "relativeAnchor": "end",
          "offset": -2,
          "endLinkMode": "auto",
          "endLinkedLayerId": null,
          "endRelativeAnchor": "end",
          "endOffset": 0,
          "text": "힌트: 없음",
          "mp3Key": "Hint_mp3",
          "mp3Url": "",
          "mp3PreGap": 0,
          "mp3PostGap": 0,
          "fontSize": 30,
          "color": "#000000",
          "textAlign": "center",
          "verticalAlign": "middle",
          "lineHeight": 2,
          "fontFamily": "BMYEONSUNG",
          "highlight": "",
          "highlightColor": "#ff0000"
        },
        {
          "id": 1753287792457,
          "name": "Answer",
          "type": "text",
          "timeMode": "부분",
          "positionMode": "부분",
          "startTime": 8.2,
          "endTime": 14.2,
          "duration": 3,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 184.99991244018707,
          "y": 393.0010040733645,
          "width": 200,
          "height": 50,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 0,
          "outlineMode": "normal",
          "canvasAlign": "custom",
          "preGap": 0,
          "postGap": 0,
          "linkMode": "relative",
          "linkedLayerId": 1753287427893,
          "relativeAnchor": "end",
          "offset": 0,
          "endLinkMode": "full",
          "endLinkedLayerId": null,
          "endRelativeAnchor": "end",
          "endOffset": 0,
          "text": "정답: ",
          "mp3Key": "Answer_mp3",
          "mp3Url": "",
          "mp3PreGap": 0,
          "mp3PostGap": 0,
          "fontSize": 30,
          "color": "#000000",
          "textAlign": "center",
          "verticalAlign": "middle",
          "lineHeight": 1,
          "fontFamily": "BMYEONSUNG",
          "highlight": "",
          "highlightColor": "#ff0000"
        },
        {
          "id": 1753369825310,
          "name": "Answer_MP3",
          "type": "audio",
          "timeMode": "부분",
          "positionMode": "부분",
          "startTime": 8.2,
          "endTime": 11.2,
          "duration": 3,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 50,
          "y": 50,
          "width": 200,
          "height": 50,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 1,
          "outlineMode": "normal",
          "canvasAlign": "custom",
          "preGap": 0,
          "postGap": 0,
          "linkMode": "relative",
          "linkedLayerId": 1753287792457,
          "relativeAnchor": "start",
          "offset": 0,
          "endLinkMode": "auto",
          "endLinkedLayerId": null,
          "endRelativeAnchor": "end",
          "endOffset": 0,
          "audioUrl": ""
        },
        {
          "id": 1753291323440,
          "name": "Explain",
          "type": "text",
          "timeMode": "부분",
          "positionMode": "부분",
          "startTime": 11.2,
          "endTime": 14.2,
          "duration": 3,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 204.99995958777856,
          "y": 532.999958970815,
          "width": 650,
          "height": 150,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 0,
          "outlineMode": "normal",
          "canvasAlign": "custom",
          "preGap": 0,
          "postGap": 0,
          "linkMode": "relative",
          "linkedLayerId": 1753287792457,
          "relativeAnchor": "end",
          "offset": 0,
          "endLinkMode": "full",
          "endLinkedLayerId": null,
          "endRelativeAnchor": "end",
          "endOffset": 0,
          "text": "설명",
          "mp3Key": "Explain_mp3",
          "mp3Url": "",
          "mp3PreGap": 0,
          "mp3PostGap": 0,
          "fontSize": 30,
          "color": "#000000",
          "textAlign": "left",
          "verticalAlign": "top",
          "lineHeight": 1,
          "fontFamily": "BMYEONSUNG",
          "highlight": "Key_Term",
          "highlightColor": "#0000ff"
        },
        {
          "id": 1753369969063,
          "name": "Explain_MP3",
          "type": "audio",
          "timeMode": "부분",
          "positionMode": "부분",
          "startTime": 11.2,
          "endTime": 14.2,
          "duration": 3,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 50,
          "y": 50,
          "width": 200,
          "height": 50,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 1,
          "outlineMode": "normal",
          "canvasAlign": "custom",
          "preGap": 0,
          "postGap": 0,
          "linkMode": "relative",
          "linkedLayerId": 1753291323440,
          "relativeAnchor": "start",
          "offset": 0,
          "endLinkMode": "auto",
          "endLinkedLayerId": null,
          "endRelativeAnchor": "end",
          "endOffset": 0,
          "audioUrl": ""
        }
      ]
    }
  }
]
'''

payload=json.loads(payload_raw)

url = f"{BASE_URL}/generate-from-layers"

# POST 요청 보내기
response = requests.post(url, json=payload)

# 응답 확인 및 출력 포맷팅
if response.status_code == 200:
    print("✅ Success!")
    try:
        res_json = response.json()
        print("📦 Response JSON:")
        print(json.dumps(res_json, indent=2, ensure_ascii=False))  # 이쁘게 출력
    except json.JSONDecodeError:
        print("⚠️ JSON 디코딩 실패:")
        print(response.text)
else:
    print(f"❌ Failed with status code: {response.status_code}")
    print("🧾 Response Text:")
    print(response.text)