import ffmpeg
import requests
import json

BASE_URL = "http://127.0.0.1:8080"

# 테스트할 데이터
payload_raw = '''
       [
  {
    "status": "ok",
    "mappedFormat": {
      "canvasRatio": "1080x720",
      "displayScale": 1,
      "layers": [
        {
          "id": 1753287418385,
          "name": "BG_Image",
          "timeMode": "전체",
          "positionMode": "전체",
          "startTime": 0,
          "endTime": 14.2,
          "duration": 14.2,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 0,
          "y": 0,
          "width": 1080,
          "height": 720,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 1,
          "outlineMode": "normal",
          "offsetPre": 0,
          "offsetPost": 0,
          "preGap": 0,
          "postGap": 0,
          "canvasAlign": "custom",
          "type": "image",
          "imgUrl": "https://drive.google.com/file/d/1vjc4FlwhjfiT6Vcb2EE1Jg0FrE3ZcFFR/view?usp=drive_link",
          "linkedStartLayerId": null,
          "linkedEndLayerId": null
        },
        {
          "id": 1753289346749,
          "name": "Image_",
          "timeMode": "전체",
          "positionMode": "부분",
          "startTime": 0,
          "endTime": 14.2,
          "duration": 14.2,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 606,
          "y": 226,
          "width": 300,
          "height": 300,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 0.6,
          "outlineMode": "normal",
          "offsetPre": 0,
          "offsetPost": 0,
          "preGap": 0,
          "postGap": 0,
          "canvasAlign": "custom",
          "type": "image",
          "imgUrl": "https://drive.google.com/file/d/1Uc4jt9pjWzH4bsa7hoFkzMeySgJfsgJF/view?usp=drive_link",
          "linkedStartLayerId": null,
          "linkedEndLayerId": null
        },
        {
          "id": 1753287426827,
          "name": "Title",
          "timeMode": "전체",
          "positionMode": "부분",
          "startTime": 0,
          "endTime": 14.2,
          "duration": 14.2,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 434,
          "y": 6.000003729925922,
          "width": 200,
          "height": 50,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 0,
          "outlineMode": "normal",
          "offsetPre": 0,
          "offsetPost": 0,
          "preGap": 0,
          "postGap": 0,
          "canvasAlign": "center",
          "type": "text",
          "text": "한국사 퀴즈",
          "mp3Key": "Title_mp3",
          "mp3Url": "",
          "mp3PreGap": 0,
          "mp3PostGap": 0,
          "fontSize": 30,
          "color": "#000000",
          "textAlign": "center"
        },
        {
          "id": 1753287427268,
          "name": "Question",
          "timeMode": "전체",
          "positionMode": "부분",
          "startTime": 0,
          "endTime": 14.2,
          "duration": 14.2,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 188,
          "y": 120,
          "width": 720,
          "height": 100,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 0,
          "outlineMode": "normal",
          "offsetPre": 0,
          "offsetPost": 0,
          "preGap": 0,
          "postGap": 0,
          "canvasAlign": "custom",
          "type": "text",
          "text": "조선왕조를 끝낸 마지막 왕의 이름은 무엇인가요?",
          "mp3Key": "Question_mp3",
          "mp3Url": "",
          "mp3PreGap": 0,
          "mp3PostGap": 0,
          "fontSize": 30,
          "color": "#000000",
          "textAlign": "left",
          "verticalAlign": "top"
        },
        {
          "id": 1753288039865,
          "name": "Question_MP3",
          "timeMode": "부분",
          "positionMode": "부분",
          "startTime": 0.2,
          "endTime": 3.2,
          "duration": 3,
          "gapBefore": 0,
          "gapAfter": 0.2,
          "x": 50,
          "y": 50,
          "width": 200,
          "height": 50,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 1,
          "outlineMode": "normal",
          "offsetPre": 0,
          "offsetPost": 0,
          "preGap": 0,
          "postGap": 0,
          "canvasAlign": "custom",
          "type": "audio",
          "audioUrl": "https://drive.google.com/file/d/1kidcqSbLFKpV-71jrpGx2BRNwTfPlVXB/view?usp=drive_link",
          "linkMode": "relative",
          "linkedLayerId": 1753287427268,
          "relativeAnchor": "start",
          "offset": 0.2
        },
        {
          "id": 1753287562780,
          "name": "Countdown",
          "timeMode": "부분",
          "positionMode": "부분",
          "startTime": 3.2,
          "endTime": 8.2,
          "duration": 5,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 527,
          "y": 300.99997872246814,
          "width": 200,
          "height": 50,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 0,
          "outlineMode": "normal",
          "offsetPre": 0,
          "offsetPost": 0,
          "preGap": 0,
          "postGap": 0,
          "canvasAlign": "custom",
          "type": "countdown",
          "countdownStart": 5,
          "fontSize": 50,
          "color": "#ff0000",
          "linkMode": "relative",
          "linkedLayerId": 1753288039865,
          "relativeAnchor": "end"
        },
        {
          "id": 1753287427893,
          "name": "Hint",
          "timeMode": "부분",
          "positionMode": "부분",
          "startTime": 6.2,
          "endTime": 8.2,
          "duration": 2,
          "gapBefore": -2,
          "gapAfter": 0,
          "x": 199,
          "y": 253.99998270670721,
          "width": 200,
          "height": 50,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 0,
          "outlineMode": "normal",
          "offsetPre": 0,
          "offsetPost": 0,
          "preGap": 0,
          "postGap": 0,
          "canvasAlign": "custom",
          "type": "text",
          "text": "ㅅㅈ",
          "mp3Key": "Hint_mp3",
          "mp3Url": "",
          "mp3PreGap": 0,
          "mp3PostGap": 0,
          "fontSize": 30,
          "color": "#000000",
          "textAlign": "center",
          "linkMode": "relative",
          "linkedLayerId": 1753287562780,
          "relativeAnchor": "end",
          "offset": -2,
          "lineHeight": 2
        },
        {
          "id": 1753287792457,
          "name": "Answer",
          "timeMode": "부분",
          "positionMode": "부분",
          "startTime": 8.2,
          "endTime": 14.2,
          "duration": 3,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 198,
          "y": 335.99997575548167,
          "width": 200,
          "height": 50,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 0,
          "outlineMode": "normal",
          "offsetPre": 0,
          "offsetPost": 0,
          "preGap": 0,
          "postGap": 0,
          "canvasAlign": "custom",
          "type": "text",
          "text": "순종",
          "mp3Key": "Answer_mp3",
          "mp3Url": "",
          "mp3PreGap": 0,
          "mp3PostGap": 0,
          "fontSize": 30,
          "color": "#000000",
          "textAlign": "center",
          "linkMode": "relative",
          "linkedLayerId": 1753287427893,
          "relativeAnchor": "end",
          "offset": 0,
          "endLinkMode": "full"
        },
        {
          "id": 1753369825310,
          "name": "Answer_MP3",
          "timeMode": "부분",
          "positionMode": "부분",
          "startTime": 8.2,
          "endTime": 11.2,
          "duration": 3,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 50,
          "y": 50,
          "width": 200,
          "height": 50,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 1,
          "outlineMode": "normal",
          "preGap": 0,
          "postGap": 0,
          "canvasAlign": "custom",
          "linkMode": "relative",
          "linkedLayerId": 1753287792457,
          "relativeAnchor": "start",
          "offset": 0,
          "endLinkMode": "auto",
          "endLinkedLayerId": null,
          "endRelativeAnchor": "end",
          "endOffset": 0,
          "type": "audio",
          "audioUrl": "https://drive.google.com/file/d/1X2B0JeOBVji2jm7SYuDoOSGxDCz-WRms/view?usp=drive_link "
        },
        {
          "id": 1753291323440,
          "name": "Explain",
          "timeMode": "부분",
          "positionMode": "부분",
          "startTime": 11.2,
          "endTime": 14.2,
          "duration": 3,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 211,
          "y": 532.999958970815,
          "width": 690,
          "height": 100,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 0,
          "outlineMode": "normal",
          "preGap": 0,
          "postGap": 0,
          "canvasAlign": "custom",
          "linkMode": "relative",
          "linkedLayerId": 1753287792457,
          "relativeAnchor": "end",
          "offset": 0,
          "type": "text",
          "text": "조선의 마지막 왕은 순종으로, 그는 대한제국의 마지막 황제이기도 합니다. 조선 왕조는 그의 통치 아래 1910년 일본에 의해 강제 병합됨으로써 역사 속에서 사라졌습니다.",
          "mp3Key": "Explain_mp3",
          "mp3Url": "",
          "mp3PreGap": 0,
          "mp3PostGap": 0,
          "fontSize": 30,
          "color": "#000000",
          "textAlign": "left",
          "lineHeight": 1,
          "verticalAlign": "top",
          "endLinkMode": "full"
        },
        {
          "id": 1753369969063,
          "name": "Explain_MP3",
          "timeMode": "부분",
          "positionMode": "부분",
          "startTime": 11.2,
          "endTime": 14.2,
          "duration": 3,
          "gapBefore": 0,
          "gapAfter": 0,
          "x": 50,
          "y": 50,
          "width": 200,
          "height": 50,
          "backgroundColor": "#ffffff",
          "backgroundOpacity": 1,
          "outlineMode": "normal",
          "preGap": 0,
          "postGap": 0,
          "canvasAlign": "custom",
          "linkMode": "relative",
          "linkedLayerId": 1753291323440,
          "relativeAnchor": "start",
          "offset": 0,
          "endLinkMode": "full",
          "endLinkedLayerId": null,
          "endRelativeAnchor": "end",
          "endOffset": 0,
          "type": "audio",
          "audioUrl": "https://drive.google.com/file/d/1Bo68nDDSYxArbT2ZSnfFdw2PLY8BS7Bb/view?usp=drive_link"
        }
      ]
    }
  }
]
'''

payload=json.loads(payload_raw)

url = f"{BASE_URL}/generate-video-from-layer"

# POST 요청 보내기
response = requests.post(url, json=payload)

# 응답 확인
if response.status_code == 200:
    print("Success!")
    print("Response JSON:", response.json())
else:
    print("Failed with status code:", response.status_code)
    print("Response:", response.text)
